name: 'code-pipeline-promote'
description: 'Promote Assignment / Release using BMI AMI DevX Code Pipeline'
branding:
  icon: play
  color: orange
inputs:
  ces_url:
    description: 'The CES url.'
    required: true
  ces_token:
    description: 'The token to use while connecting to BMC AMI DevX Code Pipeline via CES.'
    required: true
  srid:
    description: 'The ID of the instance of BMC AMI DevX Code Pipeline to connect to.'
    required: true  
  container_type:
    description: 'The container type for which you intend to promote tasks. The container type can be either A or R.'
    required: true
  container_id:
    description: 'The container id for which you intend to promote tasks.'
    required: true
  level:
    description: 'The level that the tasks exist at in the assignment.'
    required: true
  mname:
    description: 'Component with this name in the container will be promoted.'
    required: false
  mtype:
    description: 'Component with this type in the container will be promoted.'
    required: false  
  runtime_configuration:
    description: 'The runtime configuration used when connecting to BMC AMI DevX Code Pipeline.'
    required: false   
  change_type: 
    description: 'S for standard, I for incidental, or E for emergency. Default value of S.'
    required: false
    default: 'S'
  execution_status:
    description: 'I for immediate execution or at start date/time, H to create request in hold.'
    required: false
    default: 'I'
  auto_deploy:
    description: 'Generates can be set up to automatically Deploy as well by an option set up by the Code Pipeline. The default is to not use Auto Deploy. If the Auto Deploy option is set-up through Code Pipeline, then you may use this option to automatically deploy instead of using the deployAutomatically option within the DeployTask/DeployAssignment/DeployRelease actions.'
    required: true
    default: 'false'
  dpenvlst:
    description: 'The DPENVLST parameter allows you to override the environments configured for deploy at that level. If you wish to deploy to only certain environments, you can list them here, separated by a space. The length of the field is limited to 255.'
    required: false
  system:
    description: 'Allows you to specify a specific System for the Deploy.'
    required: false   
  override:
    description: 'Specify true to override a higher version of the task during promote. Use with caution.'
    required: false   
outputs:  
  is_timed_out:
    description: 'Whether the generate timed out.'
  set_id:
    description: 'The ID of the set that was used for processing.'
  url:
    description: 'The URL that can be used to retrieve information about the set that was used for processing.'
  output_json:
    description: 'the JSON output from Promote.'
runs:
  using: 'node20'
  main: 'dist/index.js'
