name: pull-request-checks
on: [pull_request]
jobs:
  build:
    name: Build action 
    runs-on: windows-latest
    steps:
      - name: Checkout Source
        uses: actions/checkout@v4

      - name: Setup NodeJS
        uses: actions/setup-node@v4

      - name: Install ncc
        run: npm i -g @vercel/ncc

      - name: Install Dependencies
        run: npm ci

      - name: Run Build
        run: ncc build index.js